# Generated by Django 5.2.4 on 2025-08-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(max_length=10),
        ),
    ]
