# Generated by Django 5.2.4 on 2025-08-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_proyecto_provincia_alter_proyecto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('plan', 'Planificado'), ('ejec', 'En ejecución'), ('fin', 'Finalizado')], default='plan', max_length=15),
        ),
    ]
